clc;
close all;


%% 1. 프로젝트 경로 설정
scriptPath = mfilename('fullpath');

if isempty(scriptPath)
    error('스크립트를 week8_2_portfolio_export.m으로 저장하세요.');
end

matlabFolder = fileparts(scriptPath);
projectRoot = fileparts(matlabFolder);

artifactFolder = fullfile(projectRoot, 'slprj');
reportFolder = fullfile(projectRoot, 'report');
figureFolder = fullfile(reportFolder, 'figures');
dataFolder = fullfile(reportFolder, 'data');

if ~isfolder(figureFolder)
    mkdir(figureFolder);
end

if ~isfolder(dataFolder)
    mkdir(dataFolder);
end


%% 2. Week 8-1 결과 불러오기
% 기존 파일명과 변경한 파일명을 모두 확인한다.

resultFile1 = fullfile( ...
    artifactFolder, ...
    'week8_1_final_comparison_results.mat');

resultFile2 = fullfile( ...
    artifactFolder, ...
    'week8_2_final_comparison_results.mat');

if isfile(resultFile1)
    resultFile = resultFile1;
elseif isfile(resultFile2)
    resultFile = resultFile2;
else
    error(['최종 비교 결과 MAT 파일을 찾을 수 없습니다.' newline ...
           'week8_1_final_comparison을 먼저 실행하세요.']);
end

load(resultFile, ...
    'finalSpeedKPI', ...
    'finalEnergyKPI', ...
    'controllerImprovement', ...
    'results');

fprintf('불러온 결과: %s\n\n', resultFile);


%% 3. KPI 표를 CSV로 저장
speedTableFile = fullfile( ...
    dataFolder, ...
    'week8_final_speed_kpi.csv');

energyTableFile = fullfile( ...
    dataFolder, ...
    'week8_final_energy_kpi.csv');

improvementTableFile = fullfile( ...
    dataFolder, ...
    'week8_controller_improvement.csv');

writetable(finalSpeedKPI, speedTableFile);
writetable(finalEnergyKPI, energyTableFile);
writetable(controllerImprovement, improvementTableFile);


%% 4. 그래프 공통 설정
caseName = string(finalSpeedKPI.Case);
numCases = numel(caseName);

colors = [
    0.85 0.20 0.20
    0.10 0.45 0.85
    0.95 0.55 0.10
    0.50 0.25 0.75
];

lineStyles = {'-', '-', '--', '-.'};


%% 5. 최종 속도 비교 그래프
speedFigure = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1400 800]);

speedAxes = axes(speedFigure);
hold(speedAxes, 'on');
grid(speedAxes, 'on');
box(speedAxes, 'on');

plot(speedAxes, ...
    results(1).Time, ...
    results(1).ReferenceSpeed, ...
    'k--', ...
    'LineWidth', 2.0, ...
    'DisplayName', 'Reference');

for k = 1:numCases
    plot(speedAxes, ...
        results(k).Time, ...
        results(k).VehicleSpeed, ...
        'Color', colors(k, :), ...
        'LineStyle', lineStyles{k}, ...
        'LineWidth', 1.7, ...
        'DisplayName', caseName(k));
end

xline(speedAxes, 30, ':', 'Uphill', ...
    'Color', [0.35 0.35 0.35], ...
    'HandleVisibility', 'off');

xline(speedAxes, 60, ':', 'Downhill', ...
    'Color', [0.35 0.35 0.35], ...
    'HandleVisibility', 'off');

xline(speedAxes, 90, ':', 'Return', ...
    'Color', [0.35 0.35 0.35], ...
    'HandleVisibility', 'off');

xlabel(speedAxes, 'Time [s]', ...
    'Color', 'k', ...
    'FontSize', 12);

ylabel(speedAxes, 'Vehicle Speed [m/s]', ...
    'Color', 'k', ...
    'FontSize', 12);

title(speedAxes, ...
    'Final Controller and Robustness Comparison', ...
    'Color', 'k', ...
    'FontSize', 14);

xlim(speedAxes, [0 150]);
ylim(speedAxes, [20 34]);

speedAxes.Color = 'w';
speedAxes.XColor = 'k';
speedAxes.YColor = 'k';
speedAxes.FontSize = 11;
speedAxes.GridColor = [0.75 0.75 0.75];

speedLegend = legend(speedAxes, ...
    'Location', 'southeast');

speedLegend.Color = 'w';
speedLegend.TextColor = 'k';
speedLegend.EdgeColor = [0.3 0.3 0.3];

speedFigureFile = fullfile( ...
    figureFolder, ...
    'week8_final_speed_comparison.png');

exportgraphics( ...
    speedFigure, ...
    speedFigureFile, ...
    'Resolution', 300);


%% 6. 기준 제어기 대비 정규화 성능 그래프
performanceMatrix = [
    finalSpeedKPI.Overall_RMSE_mps, ...
    finalSpeedKPI.Disturbance_RMSE_mps, ...
    finalSpeedKPI.Uphill_Drop_mps, ...
    finalSpeedKPI.Downhill_Rise_mps, ...
    finalSpeedKPI.Return_Drop_mps, ...
    finalSpeedKPI.Final_Error_mps
];

normalizedPerformance = ...
    performanceMatrix ./ performanceMatrix(1, :) * 100;

performanceFigure = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 800]);

performanceAxes = axes(performanceFigure);

performanceBars = bar( ...
    performanceAxes, ...
    normalizedPerformance.');

for k = 1:numCases
    performanceBars(k).FaceColor = colors(k, :);
end

grid(performanceAxes, 'on');
box(performanceAxes, 'on');

xticks(performanceAxes, 1:6);

xticklabels(performanceAxes, { ...
    'Overall RMSE', ...
    'Disturbance RMSE', ...
    'Uphill Drop', ...
    'Downhill Rise', ...
    'Return Drop', ...
    'Final Error'});

xtickangle(performanceAxes, 15);

ylabel(performanceAxes, ...
    'Baseline-normalized value [%]', ...
    'Color', 'k', ...
    'FontSize', 12);

title(performanceAxes, ...
    'Final Performance Normalized to Baseline', ...
    'Color', 'k', ...
    'FontSize', 14);

performanceAxes.Color = 'w';
performanceAxes.XColor = 'k';
performanceAxes.YColor = 'k';
performanceAxes.FontSize = 11;
performanceAxes.GridColor = [0.75 0.75 0.75];

performanceLegend = legend( ...
    performanceAxes, ...
    caseName, ...
    'Location', 'northeast');

performanceLegend.Color = 'w';
performanceLegend.TextColor = 'k';
performanceLegend.EdgeColor = [0.3 0.3 0.3];

performanceFigureFile = fullfile( ...
    figureFolder, ...
    'week8_normalized_performance.png');

exportgraphics( ...
    performanceFigure, ...
    performanceFigureFile, ...
    'Resolution', 300);


%% 7. 구동 및 제동 에너지 그래프
energyFigure = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1300 800]);

energyAxes = axes(energyFigure);

bar(energyAxes, ...
    1:numCases, ...
    [finalEnergyKPI.Traction_Energy_kWh, ...
     finalEnergyKPI.Brake_Energy_kWh], ...
    'grouped');

grid(energyAxes, 'on');
box(energyAxes, 'on');

xticks(energyAxes, 1:numCases);
xticklabels(energyAxes, caseName);
xtickangle(energyAxes, 15);

ylabel(energyAxes, ...
    'Energy [kWh]', ...
    'Color', 'k', ...
    'FontSize', 12);

title(energyAxes, ...
    'Final Traction and Brake Energy Comparison', ...
    'Color', 'k', ...
    'FontSize', 14);

energyAxes.Color = 'w';
energyAxes.XColor = 'k';
energyAxes.YColor = 'k';
energyAxes.FontSize = 11;
energyAxes.GridColor = [0.75 0.75 0.75];

energyLegend = legend(energyAxes, ...
    'Traction Energy', ...
    'Brake Energy', ...
    'Location', 'northwest');

energyLegend.Color = 'w';
energyLegend.TextColor = 'k';
energyLegend.EdgeColor = [0.3 0.3 0.3];

energyFigureFile = fullfile( ...
    figureFolder, ...
    'week8_final_energy_comparison.png');

exportgraphics( ...
    energyFigure, ...
    energyFigureFile, ...
    'Resolution', 300);


%% 8. 저장 결과 출력
fprintf('=== Week 8-2 포트폴리오 파일 저장 완료 ===\n\n');

fprintf('속도 KPI:\n%s\n\n', speedTableFile);
fprintf('에너지 KPI:\n%s\n\n', energyTableFile);
fprintf('개선율 표:\n%s\n\n', improvementTableFile);

fprintf('속도 그래프:\n%s\n\n', speedFigureFile);
fprintf('정규화 성능 그래프:\n%s\n\n', performanceFigureFile);
fprintf('에너지 그래프:\n%s\n', energyFigureFile);